# This is a basic workflow to help you get started with Actions

#name: MSVS 2022/vcpkg (2022.08.15)

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failures }}
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
        - os: windows-2022
          name: VS 2022 (Windows 2022)
          allow_failures: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Prepare cache name
        env:
          CACHE_KEY: ${{ matrix.os }}-vs-cache-${{ github.event_name }} # push for master branch pr for others

      - name: Download cache archive
        id: cache-archive
        uses: actions/cache@v3
        with:
          path: ['.ccache']
          key: ${{ CACHE_KEY }}

      - name: Setup ccache parameters and show statistics
        run: |
          ccache --set-config=compression=true
          ccache --set-config=cache_dir=${GITHUB_WORKSPACE}/.ccache
          ccache --show-stats
          ccache -p
