# This is a basic workflow to help you get started with Actions

name: MSVS 2022/vcpkg (2022.08.15)

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failures }}
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
        - os: windows-2022
          name: VS 2022 (Windows 2022)
          allow_failures: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #shell: cmd
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: dir
        shell: cmd
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        run: |
          rmdir /S /Q build
          echo "hello ${{ env.VCPKG_INSTALLATION_ROOT }}"
          echo "vc: ${VCPKG_INSTALLATION_ROOT}"
          echo "vc: %VCPKG_INSTALLATION_ROOT%"
          set VCPKG_DEFAULT_BINARY_CACHE=%cd%\vcpkg-cache
          mkdir %VCPKG_DEFAULT_BINARY_CACHE%
          cmake -B build -S . -DVCPKG_TARGET_TRIPLET=x64-windows-release -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake
          dir
          dir %VCPKG_DEFAULT_BINARY_CACHE%
